version: '3.7'

services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/app
    expose:
      - '4000'
    ports:
      - '4000:4000'
      - 9229:9229 # Used for debug
    command: npm run dev

  localstack:
    image: localstack/localstack:0.14.3
    # ports:
    # - "4566:4566"
    env_file: ./localstack.env
    volumes:
    - "./volumes/localstack:/tmp/localstack"